---
title: "Testing Phydro with daily/subdaily FluxNET data"
author: "Jaideep Joshi"
date: "2023-05-27"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rphydro)
library(tidyverse)
library(ggplot2)
library(reshape2)
```

FluxDataKit installation throws an error. Just run the R files manually for now.

```{r, echo = F, results='hide', message=FALSE, warning=F}
list = list.files("~/codes/FluxDataKit/R/")
map(paste0("~/codes/FluxDataKit/R/", list), source)
```

Read NetCDF data in Fluxnet format

```{r}
df_flux = fdk_convert_lsm(
  site="CH-Dav",
  path="~/Downloads/flux_data_kit_beta/fluxes/",
  fluxnet_format = T,
)
```

Read same data in LSM format

```{r}
df_lsm = fdk_convert_lsm(
  site="CH-Dav",
  path="~/Downloads/flux_data_kit_beta/fluxes/",
  fluxnet_format = F,
)
```


Downsample to daily using routine provided in FluxDataKit

```{r}
df_flux_daily = fdk_downsample_fluxnet(
  df_flux, 
  site = "CH-Dav")
```

Downsample to daily by simple averaging over dates

```{r, warning=F}
df_flux_daily2 = df_lsm %>% mutate(date = as.Date(time, tz="GMT")) %>% 
  group_by(date) %>% summarize_all(.funs = mean)
```


Compare Fluxnet and LSM formatted values

```{r}
df_lsm %>% filter(as.Date(time) >= as.Date("2020-06-01") &
               as.Date(time) <= as.Date("2020-06-03") ) %>% 
  with(plot(GPP~as.POSIXct(time), type="l"))
df_flux %>% filter(as.Date(as.POSIXct(TIMESTAMP_START, tz = "GMT", format="%Y%m%d%H%M")) >= as.Date("2020-06-01") &
                 as.Date(as.POSIXct(TIMESTAMP_START, tz = "GMT", format="%Y%m%d%H%M")) <= as.Date("2020-06-03") ) %>% 
  with(points(GPP_NT_VUT_REF~as.POSIXct(TIMESTAMP_START, tz = "GMT", format="%Y%m%d%H%M"), type="l", col="cyan4"))
```

Compare the two daily versions

```{r}
df_flux_daily %>% 
  with(plot(GPP_NT_VUT_REF~as.POSIXct(TIMESTAMP, tz = "GMT"), type="l", col="black"))
df_flux_daily2 %>% 
  with(points(GPP~as.POSIXct(date, tz= "GMT"), type="l", col="cyan4"))
```


```{r}
test.3day = df_lsm %>% filter(as.Date(time) >= as.Date("2020-06-01") &
                 as.Date(time) <= as.Date("2020-06-03") ) 
  
test.3day.daily = df_flux_daily2 %>% filter(as.Date(time) >= as.Date("2020-06-01") &
                                   as.Date(time) <= as.Date("2020-06-03") ) 

test.3day.daily_max = df_lsm %>% mutate(date = as.Date(time, tz="GMT")) %>% 
  group_by(date) %>% summarize_all(.funs = max)
```

```{r}

library(rphydro)

par_cost = list(alpha=0.1, gamma=1);

par_plant = list(conductivity=3e-17, psi50=-2, b=2);

options = list(gs_method = "GS_IGF", 
               et_method = "ET_DIFFUSION",
               ftemp_vj_method = "FV_kumarathunge19",
               ftemp_rd_method = "FR_heskel16",
               ftemp_br_method = "FB_atkin15",
               scale_alpha = F)



test.3day.daily.phydro = test.3day.daily %>% summarize(
  tc = Tair-273.16, 
  ppfd = (SWdown - SWup)*2, 
  vpd = VPD*100, 
  co2 = CO2air, 
  elv = elevation, 
  fapar = FPAR, 
  vwind = Wind 
)

rphydro_analytical_r = function(tc, ppfd, vpd,
                                co2, elv, fapar,
                                kphio, psi_soil, rdark,
                                vwind, par_plant, par_cost, 
                                options){
  rphydro::rphydro_analytical(tc, ppfd, vpd,
                              co2, elv, fapar,
                              kphio, psi_soil, rdark,
                              vwind, par_plant, par_cost, 
                              options)  
}


rphydro_instantaneous_analytical_r = function(vcmax25, jmax25,
                                tc, ppfd, vpd,
                                co2, elv, fapar,
                                kphio, psi_soil, rdark,
                                vwind, par_plant, par_cost, 
                                options){
  rphydro::rphydro_instantaneous_analytical(vcmax25, jmax25,
                              tc, ppfd, vpd,
                              co2, elv, fapar,
                              kphio, psi_soil, rdark,
                              vwind, par_plant, par_cost, 
                              options)  
}


acc = test.3day.daily.phydro %>% slice(1) %>% 
        purrr::pmap_dfr(.f = rphydro_analytical_r, 
                         kphio = 0.087, 
                         psi_soil = 0, 
                         rdark = 0.015, 
                         par_plant = par_plant, 
                         par_cost = par_cost, 
                         options = options)



options = list(gs_method = "GS_IGF", 
               et_method = "ET_DIFFUSION",
               ftemp_vj_method = "FV_kumarathunge19",
               ftemp_rd_method = "FR_heskel16",
               ftemp_br_method = "FB_atkin15",
               scale_alpha = F)

test.3day.phydro = test.3day %>% summarize(
    tc = Tair-273.16, 
    ppfd = (SWdown - SWup)*2, 
    vpd = VPD*100, 
    co2 = CO2air, 
    elv = elevation, 
    fapar = FPAR, 
    vwind = Wind 
  )

    
inst = test.3day.phydro %>%
        purrr::pmap_dfr(.f = rphydro_instantaneous_analytical_r,
                        vcmax25 = acc$vcmax25,
                        jmax25 = acc$jmax25,
                        kphio = 0.087, 
                        psi_soil = 0, 
                        rdark = 0.015, 
                        par_plant = par_plant, 
                        par_cost = par_cost, 
                        options = options)
        
test.3day %>% with(plot(GPP~as.POSIXct(time), type="l"))
inst %>% with(points(a~as.POSIXct(test.3day$time), type="l", col="green4"), lwd=3)       
inst %>% with(points(I(vcmax*0.5)~as.POSIXct(test.3day$time), type="l", col="green3"))
inst %>% with(points(I(dpsi*10)~as.POSIXct(test.3day$time), type="l", col="cyan3"))

test.3day.phydro %>% mutate(time = test.3day$time) %>% melt("time") %>% 
  ggplot(aes(y=value, x=as.POSIXct(time))) + 
  geom_line(col="aquamarine4") + 
  geom_vline(xintercept = 25, col="pink") + 
  theme_classic() +
  theme(strip.background = element_rect(color = "white", size = 1))+
  facet_wrap(~variable, scales = "free")

inst %>% mutate(time = test.3day$time) %>% melt("time") %>% 
  ggplot(aes(y=value, x=as.POSIXct(time))) + 
  geom_line(col="aquamarine4") + 
  geom_vline(xintercept = 25, col="pink") + 
  theme_classic() +
  theme(strip.background = element_rect(color = "white", size = 1))+
  facet_wrap(~variable, scales = "free")

```


